// <auto-generated />
using System;
using GitHubInfoDownloader.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitHubInfoDownloader.Migrations
{
    [DbContext(typeof(GitGetterContext))]
    [Migration("20221109160706_FixingMaxLength")]
    partial class FixingMaxLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GitHubInfoDownloader.Models.Commit", b =>
                {
                    b.Property<string>("sha")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("committerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("repoId")
                        .HasColumnType("int");

                    b.HasKey("sha");

                    b.HasIndex("committerId");

                    b.HasIndex("repoId");

                    b.ToTable("commits");
                });

            modelBuilder.Entity("GitHubInfoDownloader.Models.GitUser", b =>
                {
                    b.Property<int>("gitUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gitUserId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(39)
                        .HasColumnType("nvarchar(39)");

                    b.HasKey("gitUserId");

                    b.ToTable("gitUsers");
                });

            modelBuilder.Entity("GitHubInfoDownloader.Models.Repo", b =>
                {
                    b.Property<int>("repoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("repoId"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ownerId")
                        .HasColumnType("int");

                    b.HasKey("repoId");

                    b.HasIndex("ownerId");

                    b.ToTable("repos");
                });

            modelBuilder.Entity("GitHubInfoDownloader.Models.Commit", b =>
                {
                    b.HasOne("GitHubInfoDownloader.Models.GitUser", "committer")
                        .WithMany("commits")
                        .HasForeignKey("committerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitHubInfoDownloader.Models.Repo", "repo")
                        .WithMany()
                        .HasForeignKey("repoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("committer");

                    b.Navigation("repo");
                });

            modelBuilder.Entity("GitHubInfoDownloader.Models.Repo", b =>
                {
                    b.HasOne("GitHubInfoDownloader.Models.GitUser", "owner")
                        .WithMany("repos")
                        .HasForeignKey("ownerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("GitHubInfoDownloader.Models.GitUser", b =>
                {
                    b.Navigation("commits");

                    b.Navigation("repos");
                });
#pragma warning restore 612, 618
        }
    }
}
